### ISSUE TITLE
Dependencies aren't pulled with the package

### ISSUE THREAD

**Issue by grizeldi** [Delt06/urp-toon-shader#53]
In Unity 2022.2.4f1 I installed the package from git via the package manager, which should under normal circumstances pull the required dependencies into the project. However, with the urp toon shader package, I'm getting the following error:

> Library\PackageCache\com.deltation.toon-shader@231de5492d\Assets\DELTation\ToonShader\Editor\NormalsSmoothing\NormalsSmoothingUtility.cs(2,7): error CS0246: The type or namespace name 'NUnit' could not be found (are you missing a using directive or an assembly reference?)

It leads me to believe the urp toon shader package doesn't define all the packages it actually depends on, as manually installing the "Test Framework" package from Unity's package repo gets rid of the problem.

**Comment by Delt06** [comment]
Thanks for the feedback!

The package was never intended to use NUnit, that's why it's not in the dependencies. I looked into `NormalsSmoothingUtility` and turns out it was incorrectly using assertions from NUnit, while it should have used the ones from the `UnityEngine.Assertions` namespace. I pushed a fix to the master branch.

Please check if it resolves the problem.

**Comment by grizeldi** [comment]
Just tested it and it doesn't give the error anymore, thanks for the fix. Even the custom UI for the shader shows up, which I assume previously didn't because of the compilation errors, nice.
